-- ayu-dark
-- A port of the "ayu dark" palette (https://github.com/ayu-theme/ayu-colors)
-- Matches ./ayu-dark.tmuxtheme in the dotfiles root.

vim.o.termguicolors = true
vim.o.background = "dark"

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "ayu-dark"

local c = {
	-- surfaces
	bg = "#0b0e14", -- editor background
	bg_dim = "#0d1017", -- ui background (statusline, tabline)
	bg_panel = "#0f131a", -- floats, popups, sidebars
	bg_line = "#131721", -- cursorline / current line
	bg_sel = "#1a3049", -- visual selection
	bg_sel_dim = "#141f2e", -- inactive selection
	bg_search = "#2d2632", -- inactive search match
	bg_search_cur = "#6c5980", -- match under the cursor
	border = "#1c2028", -- splits, float borders

	-- text
	fg = "#bfbdb6",
	fg_idle = "#565b66", -- dimmed ui text
	comment = "#636a72",
	gutter = "#32363f", -- inactive line numbers / indent guides
	gutter_active = "#6c7380",

	-- syntax
	accent = "#e6b450", -- the ayu gold
	keyword = "#ff8f40",
	func = "#ffb454",
	operator = "#f29668",
	special = "#e6b673",
	entity = "#59c2ff",
	tag = "#39bae6",
	string = "#aad94c",
	regexp = "#95e6cb",
	constant = "#d2a6ff",
	markup = "#f07178",
	error = "#d95757",

	-- vcs / diagnostics
	added = "#7fd962",
	modified = "#73b8ff",
	removed = "#f26d78",
	warning = "#e6b450",
	info = "#39bae6",
	hint = "#95e6cb",

	none = "NONE",
}

local hl = function(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

local groups = {
	-- ── editor ──────────────────────────────────────────────────────────────
	Normal = { fg = c.fg, bg = c.bg },
	NormalNC = { fg = c.fg, bg = c.bg },
	NormalFloat = { fg = c.fg, bg = c.bg_panel },
	FloatBorder = { fg = c.border, bg = c.bg_panel },
	FloatTitle = { fg = c.accent, bg = c.bg_panel, bold = true },
	FloatFooter = { fg = c.fg_idle, bg = c.bg_panel },
	ColorColumn = { bg = c.bg_dim },
	Conceal = { fg = c.gutter_active },
	Cursor = { fg = c.bg, bg = c.accent },
	lCursor = { fg = c.bg, bg = c.accent },
	CursorIM = { fg = c.bg, bg = c.accent },
	TermCursor = { fg = c.bg, bg = c.accent },
	TermCursorNC = { bg = c.gutter_active },
	CursorColumn = { bg = c.bg_line },
	CursorLine = { bg = c.bg_line },
	LineNr = { fg = c.gutter },
	LineNrAbove = { fg = c.gutter },
	LineNrBelow = { fg = c.gutter },
	CursorLineNr = { fg = c.accent, bold = true },
	CursorLineSign = { bg = c.bg_line },
	CursorLineFold = { bg = c.bg_line },
	SignColumn = { fg = c.gutter, bg = c.none },
	FoldColumn = { fg = c.gutter, bg = c.none },
	Folded = { fg = c.fg_idle, bg = c.bg_panel },
	Directory = { fg = c.entity },
	EndOfBuffer = { fg = c.bg },
	NonText = { fg = c.gutter },
	Whitespace = { fg = c.gutter },
	SpecialKey = { fg = c.gutter },
	VertSplit = { fg = c.border, bg = c.none },
	WinSeparator = { fg = c.border, bg = c.none },
	MatchParen = { fg = c.accent, bold = true, underline = true },
	Visual = { bg = c.bg_sel },
	VisualNOS = { bg = c.bg_sel_dim },
	Search = { fg = c.fg, bg = c.bg_search },
	IncSearch = { fg = c.bg, bg = c.accent, bold = true },
	CurSearch = { fg = c.bg, bg = c.accent, bold = true },
	Substitute = { fg = c.bg, bg = c.removed },
	QuickFixLine = { bg = c.bg_sel_dim },
	Title = { fg = c.entity, bold = true },
	Question = { fg = c.string },
	MoreMsg = { fg = c.string },
	ModeMsg = { fg = c.fg, bold = true },
	MsgArea = { fg = c.fg },
	MsgSeparator = { fg = c.border, bg = c.bg_dim },
	ErrorMsg = { fg = c.error, bold = true },
	WarningMsg = { fg = c.warning },
	WinBar = { fg = c.fg, bg = c.bg, bold = true },
	WinBarNC = { fg = c.fg_idle, bg = c.bg },

	-- ── menus & prompts ─────────────────────────────────────────────────────
	Pmenu = { fg = c.fg, bg = c.bg_panel },
	PmenuSel = { fg = c.fg, bg = c.bg_sel, bold = true },
	PmenuKind = { fg = c.tag, bg = c.bg_panel },
	PmenuKindSel = { fg = c.tag, bg = c.bg_sel },
	PmenuExtra = { fg = c.fg_idle, bg = c.bg_panel },
	PmenuExtraSel = { fg = c.fg_idle, bg = c.bg_sel },
	PmenuSbar = { bg = c.bg_panel },
	PmenuThumb = { bg = c.gutter_active },
	WildMenu = { fg = c.bg, bg = c.accent },

	-- ── statusline & tabs ───────────────────────────────────────────────────
	StatusLine = { fg = c.fg, bg = c.bg_dim },
	StatusLineNC = { fg = c.fg_idle, bg = c.bg_dim },
	TabLine = { fg = c.fg_idle, bg = c.bg_dim },
	TabLineFill = { bg = c.bg_dim },
	TabLineSel = { fg = c.accent, bg = c.bg, bold = true },

	-- ── diffs ───────────────────────────────────────────────────────────────
	DiffAdd = { fg = c.added, bg = "#12200f" },
	DiffChange = { fg = c.modified, bg = "#0f1824" },
	DiffDelete = { fg = c.removed, bg = "#210f13" },
	DiffText = { fg = c.modified, bg = "#16253a" },
	diffAdded = { fg = c.added },
	diffRemoved = { fg = c.removed },
	diffChanged = { fg = c.modified },
	diffFile = { fg = c.accent },
	diffLine = { fg = c.fg_idle },
	diffIndexLine = { fg = c.constant },

	-- ── spelling ────────────────────────────────────────────────────────────
	SpellBad = { sp = c.error, undercurl = true },
	SpellCap = { sp = c.warning, undercurl = true },
	SpellLocal = { sp = c.info, undercurl = true },
	SpellRare = { sp = c.hint, undercurl = true },

	-- ── syntax (legacy groups) ──────────────────────────────────────────────
	Comment = { fg = c.comment, italic = true },
	Constant = { fg = c.constant },
	String = { fg = c.string },
	Character = { fg = c.string },
	Number = { fg = c.constant },
	Float = { fg = c.constant },
	Boolean = { fg = c.constant },
	Identifier = { fg = c.fg },
	Function = { fg = c.func },
	Statement = { fg = c.keyword },
	Conditional = { fg = c.keyword },
	Repeat = { fg = c.keyword },
	Label = { fg = c.keyword },
	Operator = { fg = c.operator },
	Keyword = { fg = c.keyword },
	Exception = { fg = c.keyword },
	PreProc = { fg = c.markup },
	Include = { fg = c.keyword },
	Define = { fg = c.keyword },
	Macro = { fg = c.special },
	PreCondit = { fg = c.keyword },
	Type = { fg = c.tag },
	StorageClass = { fg = c.keyword },
	Structure = { fg = c.tag },
	Typedef = { fg = c.tag },
	Special = { fg = c.special },
	SpecialChar = { fg = c.regexp },
	Tag = { fg = c.tag },
	Delimiter = { fg = c.fg_idle },
	SpecialComment = { fg = c.comment, italic = true, bold = true },
	Debug = { fg = c.markup },
	Underlined = { fg = c.entity, underline = true },
	Ignore = { fg = c.gutter },
	Error = { fg = c.error, bold = true },
	Todo = { fg = c.bg, bg = c.accent, bold = true },

	-- ── treesitter ──────────────────────────────────────────────────────────
	["@variable"] = { fg = c.fg },
	["@variable.builtin"] = { fg = c.markup },
	["@variable.parameter"] = { fg = c.fg },
	["@variable.parameter.builtin"] = { fg = c.markup },
	["@variable.member"] = { fg = c.tag },
	["@constant"] = { fg = c.constant },
	["@constant.builtin"] = { fg = c.constant, italic = true },
	["@constant.macro"] = { fg = c.special },
	["@module"] = { fg = c.fg },
	["@module.builtin"] = { fg = c.markup },
	["@label"] = { fg = c.keyword },
	["@string"] = { fg = c.string },
	["@string.documentation"] = { fg = c.comment, italic = true },
	["@string.regexp"] = { fg = c.regexp },
	["@string.escape"] = { fg = c.regexp },
	["@string.special"] = { fg = c.regexp },
	["@string.special.symbol"] = { fg = c.constant },
	["@string.special.url"] = { fg = c.tag, underline = true },
	["@character"] = { fg = c.string },
	["@character.special"] = { fg = c.regexp },
	["@boolean"] = { fg = c.constant },
	["@number"] = { fg = c.constant },
	["@number.float"] = { fg = c.constant },
	["@type"] = { fg = c.tag },
	["@type.builtin"] = { fg = c.tag, italic = true },
	["@type.definition"] = { fg = c.tag },
	["@attribute"] = { fg = c.special },
	["@attribute.builtin"] = { fg = c.special },
	["@property"] = { fg = c.tag },
	["@function"] = { fg = c.func },
	["@function.builtin"] = { fg = c.func, italic = true },
	["@function.call"] = { fg = c.func },
	["@function.macro"] = { fg = c.special },
	["@function.method"] = { fg = c.func },
	["@function.method.call"] = { fg = c.func },
	["@constructor"] = { fg = c.tag },
	["@operator"] = { fg = c.operator },
	["@keyword"] = { fg = c.keyword },
	["@keyword.function"] = { fg = c.keyword },
	["@keyword.operator"] = { fg = c.keyword },
	["@keyword.import"] = { fg = c.keyword },
	["@keyword.type"] = { fg = c.keyword },
	["@keyword.modifier"] = { fg = c.keyword },
	["@keyword.repeat"] = { fg = c.keyword },
	["@keyword.return"] = { fg = c.keyword },
	["@keyword.debug"] = { fg = c.markup },
	["@keyword.exception"] = { fg = c.keyword },
	["@keyword.conditional"] = { fg = c.keyword },
	["@keyword.directive"] = { fg = c.special },
	["@keyword.directive.define"] = { fg = c.special },
	["@punctuation.delimiter"] = { fg = c.fg_idle },
	["@punctuation.bracket"] = { fg = c.fg_idle },
	["@punctuation.special"] = { fg = c.regexp },
	["@comment"] = { fg = c.comment, italic = true },
	["@comment.documentation"] = { fg = c.comment, italic = true },
	["@comment.error"] = { fg = c.bg, bg = c.error, bold = true },
	["@comment.warning"] = { fg = c.bg, bg = c.warning, bold = true },
	["@comment.todo"] = { fg = c.bg, bg = c.accent, bold = true },
	["@comment.note"] = { fg = c.bg, bg = c.info, bold = true },
	["@markup.strong"] = { fg = c.accent, bold = true },
	["@markup.italic"] = { fg = c.markup, italic = true },
	["@markup.strikethrough"] = { fg = c.fg_idle, strikethrough = true },
	["@markup.underline"] = { underline = true },
	["@markup.heading"] = { fg = c.accent, bold = true },
	["@markup.heading.1"] = { fg = c.keyword, bold = true },
	["@markup.heading.2"] = { fg = c.accent, bold = true },
	["@markup.heading.3"] = { fg = c.string, bold = true },
	["@markup.heading.4"] = { fg = c.regexp, bold = true },
	["@markup.heading.5"] = { fg = c.entity, bold = true },
	["@markup.heading.6"] = { fg = c.constant, bold = true },
	["@markup.quote"] = { fg = c.fg_idle, italic = true },
	["@markup.math"] = { fg = c.regexp },
	["@markup.link"] = { fg = c.tag },
	["@markup.link.label"] = { fg = c.tag },
	["@markup.link.url"] = { fg = c.fg_idle, underline = true },
	["@markup.raw"] = { fg = c.string },
	["@markup.raw.block"] = { fg = c.fg },
	["@markup.list"] = { fg = c.operator },
	["@markup.list.checked"] = { fg = c.added },
	["@markup.list.unchecked"] = { fg = c.fg_idle },
	["@tag"] = { fg = c.tag },
	["@tag.builtin"] = { fg = c.tag },
	["@tag.attribute"] = { fg = c.func },
	["@tag.delimiter"] = { fg = c.fg_idle },
	["@diff.plus"] = { fg = c.added },
	["@diff.minus"] = { fg = c.removed },
	["@diff.delta"] = { fg = c.modified },

	-- ── lsp semantic tokens ─────────────────────────────────────────────────
	["@lsp.type.class"] = { link = "@type" },
	["@lsp.type.comment"] = {},
	["@lsp.type.decorator"] = { link = "@attribute" },
	["@lsp.type.enum"] = { link = "@type" },
	["@lsp.type.enumMember"] = { link = "@constant" },
	["@lsp.type.function"] = { link = "@function" },
	["@lsp.type.interface"] = { link = "@type" },
	["@lsp.type.macro"] = { link = "@function.macro" },
	["@lsp.type.method"] = { link = "@function.method" },
	["@lsp.type.namespace"] = { link = "@module" },
	["@lsp.type.parameter"] = { link = "@variable.parameter" },
	["@lsp.type.property"] = { link = "@property" },
	["@lsp.type.struct"] = { link = "@type" },
	["@lsp.type.type"] = { link = "@type" },
	["@lsp.type.typeParameter"] = { link = "@type.definition" },
	["@lsp.type.variable"] = { link = "@variable" },
	["@lsp.mod.readonly"] = { link = "@constant" },
	["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
	["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
	["@lsp.typemod.variable.readonly"] = { link = "@constant" },

	-- ── diagnostics ─────────────────────────────────────────────────────────
	DiagnosticError = { fg = c.error },
	DiagnosticWarn = { fg = c.warning },
	DiagnosticInfo = { fg = c.info },
	DiagnosticHint = { fg = c.hint },
	DiagnosticOk = { fg = c.added },
	DiagnosticVirtualTextError = { fg = c.error, bg = "#1a1014" },
	DiagnosticVirtualTextWarn = { fg = c.warning, bg = "#191509" },
	DiagnosticVirtualTextInfo = { fg = c.info, bg = "#0e1820" },
	DiagnosticVirtualTextHint = { fg = c.hint, bg = "#0e1a1a" },
	DiagnosticVirtualTextOk = { fg = c.added, bg = "#101a0e" },
	DiagnosticUnderlineError = { sp = c.error, undercurl = true },
	DiagnosticUnderlineWarn = { sp = c.warning, undercurl = true },
	DiagnosticUnderlineInfo = { sp = c.info, undercurl = true },
	DiagnosticUnderlineHint = { sp = c.hint, undercurl = true },
	DiagnosticUnderlineOk = { sp = c.added, undercurl = true },
	DiagnosticUnnecessary = { fg = c.comment, undercurl = true, sp = c.comment },
	DiagnosticDeprecated = { fg = c.comment, strikethrough = true },
	DiagnosticFloatingError = { fg = c.error, bg = c.bg_panel },
	DiagnosticFloatingWarn = { fg = c.warning, bg = c.bg_panel },
	DiagnosticFloatingInfo = { fg = c.info, bg = c.bg_panel },
	DiagnosticFloatingHint = { fg = c.hint, bg = c.bg_panel },

	-- ── lsp ─────────────────────────────────────────────────────────────────
	LspReferenceText = { bg = c.bg_sel_dim },
	LspReferenceRead = { bg = c.bg_sel_dim },
	LspReferenceWrite = { bg = c.bg_sel_dim, underline = true },
	LspInlayHint = { fg = c.gutter_active, bg = c.bg_dim, italic = true },
	LspCodeLens = { fg = c.comment, italic = true },
	LspSignatureActiveParameter = { fg = c.accent, bold = true },
	LspInfoBorder = { fg = c.border, bg = c.bg_panel },

	-- ── gitsigns / diffview ─────────────────────────────────────────────────
	GitSignsAdd = { fg = c.added },
	GitSignsChange = { fg = c.modified },
	GitSignsDelete = { fg = c.removed },
	GitSignsAddNr = { fg = c.added },
	GitSignsChangeNr = { fg = c.modified },
	GitSignsDeleteNr = { fg = c.removed },
	GitSignsAddLn = { bg = "#12200f" },
	GitSignsChangeLn = { bg = "#0f1824" },
	GitSignsDeleteLn = { bg = "#210f13" },
	GitSignsCurrentLineBlame = { fg = c.gutter, italic = true },
	DiffviewNormal = { fg = c.fg, bg = c.bg_dim },
	DiffviewFilePanelTitle = { fg = c.accent, bold = true },
	DiffviewFilePanelCounter = { fg = c.constant, bold = true },
	DiffviewFilePanelFileName = { fg = c.fg },
	DiffviewStatusAdded = { fg = c.added },
	DiffviewStatusModified = { fg = c.modified },
	DiffviewStatusDeleted = { fg = c.removed },

	-- ── telescope ───────────────────────────────────────────────────────────
	TelescopeNormal = { fg = c.fg, bg = c.bg_panel },
	TelescopeBorder = { fg = c.border, bg = c.bg_panel },
	TelescopeTitle = { fg = c.bg, bg = c.accent, bold = true },
	TelescopePromptNormal = { fg = c.fg, bg = c.bg_line },
	TelescopePromptBorder = { fg = c.bg_line, bg = c.bg_line },
	TelescopePromptTitle = { fg = c.bg, bg = c.keyword, bold = true },
	TelescopePromptPrefix = { fg = c.accent },
	TelescopePromptCounter = { fg = c.fg_idle },
	TelescopeResultsNormal = { fg = c.fg, bg = c.bg_panel },
	TelescopeResultsBorder = { fg = c.bg_panel, bg = c.bg_panel },
	TelescopeResultsTitle = { fg = c.bg_panel, bg = c.bg_panel },
	TelescopePreviewNormal = { fg = c.fg, bg = c.bg_panel },
	TelescopePreviewBorder = { fg = c.bg_panel, bg = c.bg_panel },
	TelescopePreviewTitle = { fg = c.bg, bg = c.string, bold = true },
	TelescopeSelection = { fg = c.fg, bg = c.bg_sel, bold = true },
	TelescopeSelectionCaret = { fg = c.accent, bg = c.bg_sel },
	TelescopeMultiSelection = { fg = c.constant, bg = c.bg_sel_dim },
	TelescopeMatching = { fg = c.accent, bold = true },

	-- ── blink.cmp ───────────────────────────────────────────────────────────
	BlinkCmpMenu = { fg = c.fg, bg = c.bg_panel },
	BlinkCmpMenuBorder = { fg = c.border, bg = c.bg_panel },
	BlinkCmpMenuSelection = { bg = c.bg_sel, bold = true },
	BlinkCmpScrollBarThumb = { bg = c.gutter_active },
	BlinkCmpScrollBarGutter = { bg = c.bg_panel },
	BlinkCmpLabel = { fg = c.fg },
	BlinkCmpLabelDeprecated = { fg = c.comment, strikethrough = true },
	BlinkCmpLabelMatch = { fg = c.accent, bold = true },
	BlinkCmpLabelDetail = { fg = c.fg_idle },
	BlinkCmpLabelDescription = { fg = c.fg_idle },
	BlinkCmpKind = { fg = c.tag },
	BlinkCmpKindFunction = { fg = c.func },
	BlinkCmpKindMethod = { fg = c.func },
	BlinkCmpKindVariable = { fg = c.fg },
	BlinkCmpKindKeyword = { fg = c.keyword },
	BlinkCmpKindText = { fg = c.string },
	BlinkCmpKindSnippet = { fg = c.regexp },
	BlinkCmpKindClass = { fg = c.tag },
	BlinkCmpKindConstant = { fg = c.constant },
	BlinkCmpSource = { fg = c.comment },
	BlinkCmpDoc = { fg = c.fg, bg = c.bg_panel },
	BlinkCmpDocBorder = { fg = c.border, bg = c.bg_panel },
	BlinkCmpDocSeparator = { fg = c.border, bg = c.bg_panel },
	BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_panel },
	BlinkCmpSignatureHelpBorder = { fg = c.border, bg = c.bg_panel },
	BlinkCmpSignatureHelpActiveParameter = { fg = c.accent, bold = true },
	BlinkCmpGhostText = { fg = c.gutter_active, italic = true },

	-- ── oil ─────────────────────────────────────────────────────────────────
	OilDir = { fg = c.entity, bold = true },
	OilDirIcon = { fg = c.entity },
	OilFile = { fg = c.fg },
	OilLink = { fg = c.regexp },
	OilLinkTarget = { fg = c.comment, italic = true },
	OilSocket = { fg = c.constant },
	OilCreate = { fg = c.added },
	OilDelete = { fg = c.removed },
	OilMove = { fg = c.modified },
	OilCopy = { fg = c.accent },
	OilChange = { fg = c.modified },
	OilRestore = { fg = c.string },
	OilPurge = { fg = c.error },
	OilTrash = { fg = c.removed },

	-- ── bufferline ──────────────────────────────────────────────────────────
	BufferLineFill = { bg = c.bg_dim },
	BufferLineBackground = { fg = c.fg_idle, bg = c.bg_dim },
	BufferLineBufferVisible = { fg = c.fg_idle, bg = c.bg_dim },
	BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true, italic = false },
	BufferLineSeparator = { fg = c.bg_dim, bg = c.bg_dim },
	BufferLineSeparatorVisible = { fg = c.bg_dim, bg = c.bg_dim },
	BufferLineSeparatorSelected = { fg = c.bg_dim, bg = c.bg },
	BufferLineIndicatorSelected = { fg = c.accent, bg = c.bg },
	BufferLineIndicatorVisible = { fg = c.bg_dim, bg = c.bg_dim },
	BufferLineModified = { fg = c.string, bg = c.bg_dim },
	BufferLineModifiedVisible = { fg = c.string, bg = c.bg_dim },
	BufferLineModifiedSelected = { fg = c.string, bg = c.bg },
	BufferLineCloseButton = { fg = c.fg_idle, bg = c.bg_dim },
	BufferLineCloseButtonVisible = { fg = c.fg_idle, bg = c.bg_dim },
	BufferLineCloseButtonSelected = { fg = c.markup, bg = c.bg },
	BufferLineDuplicate = { fg = c.comment, bg = c.bg_dim, italic = true },
	BufferLineDuplicateVisible = { fg = c.comment, bg = c.bg_dim, italic = true },
	BufferLineDuplicateSelected = { fg = c.comment, bg = c.bg, italic = true },
	BufferLineNumbers = { fg = c.fg_idle, bg = c.bg_dim },
	BufferLineNumbersSelected = { fg = c.accent, bg = c.bg, bold = true },
	BufferLineError = { fg = c.error, bg = c.bg_dim },
	BufferLineErrorSelected = { fg = c.error, bg = c.bg },
	BufferLineWarning = { fg = c.warning, bg = c.bg_dim },
	BufferLineWarningSelected = { fg = c.warning, bg = c.bg },

	-- ── snacks (dashboard, notifier, picker) ────────────────────────────────
	SnacksNormal = { fg = c.fg, bg = c.bg },
	SnacksWinBar = { fg = c.accent, bg = c.bg_dim, bold = true },
	SnacksBackdrop = { bg = c.bg },
	SnacksDashboardHeader = { fg = c.accent },
	SnacksDashboardIcon = { fg = c.keyword },
	SnacksDashboardTitle = { fg = c.entity, bold = true },
	SnacksDashboardDesc = { fg = c.fg },
	SnacksDashboardKey = { fg = c.operator },
	SnacksDashboardFile = { fg = c.tag },
	SnacksDashboardDir = { fg = c.comment },
	SnacksDashboardFooter = { fg = c.comment, italic = true },
	SnacksDashboardSpecial = { fg = c.constant },
	SnacksNotifierInfo = { fg = c.info, bg = c.bg_panel },
	SnacksNotifierWarn = { fg = c.warning, bg = c.bg_panel },
	SnacksNotifierError = { fg = c.error, bg = c.bg_panel },
	SnacksNotifierDebug = { fg = c.comment, bg = c.bg_panel },
	SnacksNotifierTrace = { fg = c.constant, bg = c.bg_panel },
	SnacksNotifierBorderInfo = { fg = c.info, bg = c.bg_panel },
	SnacksNotifierBorderWarn = { fg = c.warning, bg = c.bg_panel },
	SnacksNotifierBorderError = { fg = c.error, bg = c.bg_panel },
	SnacksNotifierTitleInfo = { fg = c.info, bold = true },
	SnacksNotifierTitleWarn = { fg = c.warning, bold = true },
	SnacksNotifierTitleError = { fg = c.error, bold = true },
	SnacksIndent = { fg = c.gutter },
	SnacksIndentScope = { fg = c.gutter_active },

	-- ── fidget ──────────────────────────────────────────────────────────────
	FidgetTask = { fg = c.comment },
	FidgetTitle = { fg = c.accent, bold = true },

	-- ── render-markdown ─────────────────────────────────────────────────────
	RenderMarkdownH1Bg = { fg = c.keyword, bg = "#1c1410" },
	RenderMarkdownH2Bg = { fg = c.accent, bg = "#1b1710" },
	RenderMarkdownH3Bg = { fg = c.string, bg = "#161a0f" },
	RenderMarkdownH4Bg = { fg = c.regexp, bg = "#101a18" },
	RenderMarkdownH5Bg = { fg = c.entity, bg = "#0f1720" },
	RenderMarkdownH6Bg = { fg = c.constant, bg = "#16121f" },
	RenderMarkdownCode = { bg = c.bg_dim },
	RenderMarkdownCodeInline = { fg = c.string, bg = c.bg_panel },
	RenderMarkdownBullet = { fg = c.operator },
	RenderMarkdownQuote = { fg = c.fg_idle },
	RenderMarkdownDash = { fg = c.border },
	RenderMarkdownLink = { fg = c.tag },
	RenderMarkdownUnchecked = { fg = c.fg_idle },
	RenderMarkdownChecked = { fg = c.added },
	RenderMarkdownTableHead = { fg = c.tag },
	RenderMarkdownTableRow = { fg = c.fg_idle },

	-- ── misc plugins ────────────────────────────────────────────────────────
	ModesCopy = { bg = c.accent },
	ModesDelete = { bg = c.removed },
	ModesInsert = { bg = c.regexp },
	ModesReplace = { bg = c.operator },
	ModesVisual = { bg = c.constant },
	SupermavenSuggestion = { fg = c.gutter_active, italic = true },
	TreesitterContext = { bg = c.bg_dim },
	TreesitterContextLineNumber = { fg = c.gutter_active, bg = c.bg_dim },
	WhichKey = { fg = c.operator },
	WhichKeyGroup = { fg = c.entity },
	WhichKeyDesc = { fg = c.fg },
	WhichKeySeparator = { fg = c.comment },
	WhichKeyFloat = { bg = c.bg_panel },
	WhichKeyValue = { fg = c.comment },
	MiniAnimateCursor = { reverse = true, nocombine = true },
	healthSuccess = { fg = c.added },
	healthWarning = { fg = c.warning },
	healthError = { fg = c.error },
}

for group, opts in pairs(groups) do
	hl(group, opts)
end

-- ── :terminal palette ───────────────────────────────────────────────────────
vim.g.terminal_color_0 = "#01060e"
vim.g.terminal_color_1 = "#ea6c73"
vim.g.terminal_color_2 = "#91b362"
vim.g.terminal_color_3 = "#f9af4f"
vim.g.terminal_color_4 = "#53bdfa"
vim.g.terminal_color_5 = "#d2a6ff"
vim.g.terminal_color_6 = "#90e1c6"
vim.g.terminal_color_7 = "#c7c7c7"
vim.g.terminal_color_8 = "#686868"
vim.g.terminal_color_9 = "#f07178"
vim.g.terminal_color_10 = "#c2d94c"
vim.g.terminal_color_11 = "#ffb454"
vim.g.terminal_color_12 = "#59c2ff"
vim.g.terminal_color_13 = "#e6b3ff"
vim.g.terminal_color_14 = "#95e6cb"
vim.g.terminal_color_15 = "#ffffff"
